little_lemon/little_lemon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls', namespace='restaurant'))
]

little_lemon/restaurant/urls.py
from django.urls import path, re_path 
from . import views
app_name='restaurant'
urlpatterns =[
    path('',views.home, name='home'),
    path('about/',views.about, name='about'),
    path('menu/',views.menu, name='menu'),
    re_path('book/',views.book, name='book'),
    path('menu_item/<int:pk>', views.display_menu_items, name="menu_item"),
]

little_lemon/restaurant/models.py
from django.db import models

# Create your models here.
class Booking(models.Model):
    first_name=models.CharField(max_length=200)
    last_name=models.CharField(max_length=200)
    guest_count = models.IntegerField()
    reservation_time = models.DateField(auto_now=True)
    comments = models.CharField(max_length=1000)

class Menu(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField(max_length=1000,default='')

little_lemon/restaurant/forms.py
from .models import Booking
from django import forms

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = "__all__"
        

little_lemon/restaurant/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import BookingForm
from .models import Menu

# Create your views here.
def home(request):
    return render(request, "home.html", {})

def about(request):
    about_content = {'about': "Little Lemon is a family-owned Mediterranean restaurant, focused on traditional recipes served with a modern twist. The chefs draw inspiration from Italian, Greek, and Turkish culture and have a menu of 12-15 items that they rotate seasonally. The restaurant has a rustic and relaxed atmosphere with moderate prices, making it a popular place for a meal any time of the day."} 
    
    return render(request, 'about.html', about_content)

def menu(request):
    menu_all = Menu.objects.all().order_by('name')
    menu_dict = {"menu": menu_all}
    return render(request, 'menu.html', menu_dict)

def book(request):
    form = BookingForm()
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
    context = {"form":form}
    return render(request,"booking.html", context)

def display_menu_items(request, pk=None):
    if pk:
        menu_item = Menu.objects.get(pk=pk)
    else:
        menu_item = ""
    
    context = {"menu_item": menu_item}
    return render(request, "menu_item.html", context)

little_lemon/restaurant/templates/about.html
{% extends "base.html" %} {% block contents %}
<h1>About</h1>
<p>{{about}}</p>
{% endblock %}

little_lemon/restaurant/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Little Lemon</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist."
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <!--Header Content-->
    {% include "partials/_header.html" %}
    <main>{% block contents %} {% endblock %}</main>
    <!--Footer Content-->
    {% include "partials/_footer.html" %}
  </body>
</html>

little_lemon/restaurant/templates/booking.html
{% extends 'base.html' %} {% load static %} {% block contents %}
<section>
  <article>
    <h1>Make a reservation</h1>
    <!--Begin row-->
    <div class="row">
      <!--Begin col-->
      <div class="column">
        <form action="" method="post">
          {% csrf_token %} {{form.as_p}}
          <input type="submit" id="button" />
        </form>
      </div>
      <!--End col-->

      <!--Begin col-->
      <div class="column">
        <div class="videowrap">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11898.289517452584!2d-87.60853049433447!3d41.79442860243028!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e2912ce6f7027%3A0xc0cfb5545d4a37b2!2sHyde%20Park%2C%20Chicago%2C%20IL%2C%20USA!5e0!3m2!1sen!2spt!4v1662384760663!5m2!1sen!2spt"
            width="600"
            height="450"
            style="border: 0"
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
          ></iframe>
        </div>
      </div>
      <!--End col-->
    </div>
    <!--End row-->
  </article>
</section>
{% endblock %}

little_lemon/restaurant/templates/home.html
{% extends 'base.html' %} {% load static %} {% block contents %}
<section>
  <article id="hero">
    <h1 class="heading_shadow" style="color: white">SPECIAL OFFER</h1>
    <p>30% Off This Weekend</p>
    <a href="#" class="cta"> Book now </a>
  </article>
</section>
<section>
  <article>
    <h2>Our New Menu</h2>
    <img src="{% static 'img/grill.jpg' %}" />
    <p>
      Our menu consists of 12-15 seasonal items based on Italian, Greek, and
      Turkish culture.
    </p>
    <p>
      <a href="{% url 'restaurant:menu' %}">See our new menu</a>
    </p>
  </article>
  <article>
    <h2>Book a table</h2>
    <img src="{% static 'img/salad.jpg' %}" />
    <p>
      Reserve your table for an Italian, Greek, and Turkish dining experience.
    </p>
    <p>
      <a href="{% url 'restaurant:book' %}">Book your table now</a>
    </p>
  </article>
  <article>
    <h2>Opening Hours</h2>
    <img src="{% static 'img/head_chef.jpg' %}" />
    <p>
      The Little Lemon Restaurant is open 7 days a week, except for public
      holidays.
    </p>
    <ul>
      <li>Mon - Fri: 2pm - 10pm</li>
      <li>Sat: 2pm - 11pm</li>
      <li>Sun: 2pm - 9pm</li>
    </ul>
  </article>
</section>
{% endblock %}

little_lemon/restaurant/templates/menu.html
{% extends "base.html" %} {% load static %} {% block contents %}
<h1>Menu</h1>
{% if menu %}
<!--Begin col-->
<div class="column">
  {% for item in menu%}
  <p>
    <a href="{% url 'restaurant:menu_item' pk=item.pk %}"> {{item.name}} </a>
    <span class="menu-price">$ {{item.price}}.00 </span>
  </p>
  {% endfor %}
</div>
<!--End col-->
{% else %}
<p>No Items to Display</p>
{% endif %} {% endblock %}

little_lemon/restaurant/templates/menu_item.html
{% extends 'base.html' %} {% load static %} {% block contents %}
<section>
  <article>
    <h1>Menu item</h1>
    <span>
      <a href="{% url 'restaurant:home' %}">Home</a> /
      <a href="{% url 'restaurant:menu' %}">Menu</a>/ {{ menu_item.name }}
    </span>
    <!--Begin row-->
    <div class="row">
      <!--Begin col-->
      <div class="column">
        <h2>{{ menu_item.name }}</h2>
        <p>{{ menu_item.description }}</p>
        <p>Price: ${{ menu_item.price }}.00</p>
      </div>
      <!--End col-->
      <!--Begin col-->
      <div class="column">
        <img
          src="../static/img/menu_items/{{menu_item.name}}.jpg"
          alt="{{ menu_item.name}}"
        />
      </div>
      <!--End col-->
    </div>
    <!--End row-->
  </article>
</section>
{% endblock %}

little_lemon/restaurant/templates/partials/_footer.html
{% load static %}
<footer>
  <article>
    <img src="{% static 'img/logo_footer.png' %}" />
  </article>
  <article>
    <p>Copyright Little Lemon</p>
  </article>
</footer>

little_lemon/restaurant/templates/partials/_header.html
{% load static %}

<header>
  <img src="{% static 'img/logo.png' %}" />
</header>
<nav>
  <ul>
    <li><a href="{% url 'restaurant:home' %}">Home</a></li>
    <li><a href="{% url 'restaurant:about' %}">About</a></li>
    <li><a href="{% url 'restaurant:menu' %}">Menu</a></li>
    <li><a href="{% url 'restaurant:book' %}">Book</a></li>
  </ul>
</nav>